server:
  port: 8087

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/authuser
    username: postgres
    password: ${database_password}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ "health","prometheus", "metrics" ]
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true

